 db:
  ip: "localhost"
  username: "root"
  password: "secretpass"
  database: "impulse_development"
  port: 3306

   apis:
  steam_key: "XXXXXXXXXXXXXXXXXXXXXXX"
  slack_webhook: "https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX"
